### ISSUE TITLE
Add Support Vector Regression

### ISSUE THREAD

**Issue by anuragc2001** [DSCKGEC/learn-machine-learn#10]
**Is your feature request related to a problem? Please describe.**
The Support Vector Regression block has been left incomplete. This feature will further help us to implement another regression model with which we can predict the model with more accuracy. 

**Describe the solution you'd like**
Implement Support Vector Regression on the given dataset given with the required preprocessed entities

**Comment by A1zenSousuke** [comment]
Hello @anuragc2001 , can you assign this issue to me?

**Comment by anuragc2001** [comment]
Sure @kpratik1929. I've assigned you the issue. Go ahead!

**Comment by A1zenSousuke** [comment]
Hey @anuragc2001 , I have added the support vector regression. Can you check it?

**Comment by anuragc2001** [comment]
@kpratik1929 I've mentioned some points in your PR, please do through them once.

**Comment by anuragc2001** [comment]
@kpratik1929 Well done with the job! I'm closing this issue.

**Comment by anuragc2001** [comment]
@kpratik1929 Please reopen a PR merging into the main branch directly.
