### ISSUE TITLE
Improve the Random Forest Regression model already implemented on the dataset

### ISSUE THREAD

**Issue by anuragc2001** [DSCKGEC/learn-machine-learn#12]
Is your feature request related to a problem? Please describe.
The Random Forest Regression code is not predicting results with much accuracy. This feature will further help us to implement another regression model with which we can predict the model with more accuracy.

Describe the solution you'd like
Improve the accuracy of the Random Forest Regression on the given dataset given with the required preprocessed entities

**Comment by Codehackerone** [comment]
gg

**Comment by A1zenSousuke** [comment]
@anuragc2001 can you assign this issue to me?

**Comment by anuragc2001** [comment]
@kpratik1929 Issue assigned!

**Comment by anuragc2001** [comment]
@kpratik1929 what is your update on this issue? Do you need any help?
