### ISSUE TITLE
Add R_2 scores for all the models respectively

### ISSUE THREAD

**Issue by anuragc2001** [DSCKGEC/learn-machine-learn#13]
Is your feature request related to a problem? Please describe.
The R_2 scores block has been left incomplete. This feature will further help us to visualize the accuracies of all the models at a glance and will help us to pick up the better fitted algorithm on the dataset.

Describe the solution you'd like
Implement R_2 scores on the given dataset given with the predicted model values

**Comment by A1zenSousuke** [comment]
@anuragc2001 can you assign this issue to me?

**Comment by anuragc2001** [comment]
@kpratik1929 go ahead!

**Comment by A1zenSousuke** [comment]
@anuragc2001 this issue is solved but my previous PR is still not merged so should I open PR for this or wait?

**Comment by anuragc2001** [comment]
@kpratik1929 open a PR for this. Both the files are different.

**Comment by A1zenSousuke** [comment]
@anuragc2001 I am not able open another PR. Can you help me here?

**Comment by anuragc2001** [comment]
@kpratik1929 what's your issue? attach a screenshot.

**Comment by A1zenSousuke** [comment]
@anuragc2001 how do I reset my repo?

**Comment by anuragc2001** [comment]
@kpratik1929 remove your existing code and copy it somewhere. Delete your folder and then re-clone the project in your directory. Then add your code. Open a PR.

**Comment by A1zenSousuke** [comment]
@anuragc2001  but the forked repo already has every changes so even if I clone again I think those commits will be still there. you can see the changes [here](https://www.awesomescreenshot.com/image/30753648?key=dcc51b898b59de344466e4264be35fc8)

**Comment by anuragc2001** [comment]
@kpratik1929 wait let me reopen the pull request and I've requested for some changes please do that and I'll directly merge it from there.
