### ISSUE TITLE
Add Ridge Classifier

### ISSUE THREAD

**Issue by KrishnenduDakshi2002** [DSCKGEC/learn-machine-learn#2]
The Ridge Classifier, based on Ridge regression method, converts the label data into [-1, 1] and solves the problem with regression method. The highest value in prediction is accepted as a target class.

### **Requested Feature**

Build a Ridge classifier and in the output, f1-score, accuracy and confusion matrix must be printed, there is a function named metrics for printing the accuracy and confusion matrix.
Hyperparameter tuning can be done to improve the accuracy. As the dataset is imbalanced, do prefer f1 score as metric while training.

**Comment by A1zenSousuke** [comment]
@KrishnenduDakshi2002 can you assign this issue to me?

**Comment by KrishnenduDakshi2002** [comment]
Yeah sure @kpratik1929 , issue is assigned to you.

**Comment by anuragc2001** [comment]
@KrishnenduDakshi2002 the issues has been closed. @kpratik1929 has resolved this in a previous PR. I'm closing this.
