### ISSUE TITLE
Add Random Forest Classifier

### ISSUE THREAD

**Issue by KrishnenduDakshi2002** [DSCKGEC/learn-machine-learn#3]
A random forest is a meta estimator that fits a number of decision tree classifiers on various sub-samples of the dataset and uses averaging to improve the predictive accuracy and control over-fitting.

### **Requested Feature**

Build a Random Forest classifier and in the output, f1-score, accuracy and confusion matrix must be printed, there is a function named metrics for printing the accuracy and confusion matrix.
Hyperparameter tuning can be done to improve the accuracy. As the dataset is imbalanced, do prefer f1 score as metric while training.

**Comment by muhammadanas0716** [comment]
I wish to solve this issue!

**Comment by KrishnenduDakshi2002** [comment]
> I wish to solve this issue!

Sure @muhammadanas365 I've assigned you the issue. Go ahead!

**Comment by muhammadanas0716** [comment]
Thank you! One more thing, how am I supposed to push the request? One of your colleagues said I should publish on some other branch rather than on the main branch?

**Comment by KrishnenduDakshi2002** [comment]
you will create a pull request to  "dev" branch under main branch of this repo.

**Comment by anuragc2001** [comment]
@muhammadanas365 Sorry to bother you but from now on please open a PR merging your branch to the main branch instead of pushing it to dev. The issue we faced was that the PR's in the dev branch were not tracked by the leaderboard. 
Sorry for the inconvenience. Continue with your work.

**Comment by anuragc2001** [comment]
@muhammadanas365 What's your update? If you're facing any issue let us know. We're eagerly waiting for your PR and we want you to take up another issue. The more you solve, the better score you get in the final results.

**Comment by muhammadanas0716** [comment]
Just did. Sorry was doing some extra EDA

**Comment by anuragc2001** [comment]
@muhammadanas365 Alright! We're looking through your PR. In the meantime if you want to take some new issues feel free to comment under them.

**Comment by muhammadanas0716** [comment]
Let's first get this merges then I'd be glad to solve another issue 😁

**Comment by anuragc2001** [comment]
@muhammadanas365 Well done! Issue closed.
