### ISSUE TITLE
Add Logistic Regression

### ISSUE THREAD

**Issue by KrishnenduDakshi2002** [DSCKGEC/learn-machine-learn#4]
###**Requested Feature**

Build a Logistic Regression model and in the output, f1-score, accuracy and confusion matrix must be printed, there is a function named metrics for printing the accuracy and confusion matrix.
Hyperparameter tuning can be done to improve the accuracy. As the dataset is imbalanced, do prefer f1 score as metric while training.

**Comment by A1zenSousuke** [comment]
@KrishnenduDakshi2002 can you assign this issue to me?

**Comment by KrishnenduDakshi2002** [comment]
Hi @kpratik1929 issue is assigned to you, happy contributing.

**Comment by KrishnenduDakshi2002** [comment]
Closing this issue.
Issue resolved in commit 2950120bdbb01095610ea1db7793b3827c00d407
