### ISSUE TITLE
Improvement in Naive Bayes model

### ISSUE THREAD

**Issue by KrishnenduDakshi2002** [DSCKGEC/learn-machine-learn#7]
A Naive Bayes model is already present in the classification notebook.

**Confusion Matrix**
True positive (TP): Prediction is +ve and X is Cancerous, we want that
True negative (TN): Prediction is -ve and X is healthy, we want that too
False positive (FP): Prediction is +ve and X is healthy, false alarm, bad
False negative (FN): Prediction is -ve and X is Cancerous, the worst

### **Requested Feature**

improvement in model prediction ( less False positive and less false negative(need more attention and improvement))
Cross validation or hyper parameter tuning can be done to improve the model.

### About metrics
Choose Recall if the idea of false positives is far better than false negatives, in other words, if the occurrence of false negatives is unaccepted/intolerable, that you’d rather get some extra false positives(false alarms) over saving some false negatives, like in our cancerous example.

**Comment by srini047** [comment]
I would like to take up the issue.

**Comment by KrishnenduDakshi2002** [comment]
Hi  @srini047 , I assigned the issue. Go ahead.
