### ISSUE TITLE
Add a function to Visualize the  Confusion matrix

### ISSUE THREAD

**Issue by KrishnenduDakshi2002** [DSCKGEC/learn-machine-learn#8]
## **Requested Feature**
create a python function which will take y_true and y_pred as arguments and output will look like the following picture - 

![1*dnMEzkfO_PokQAXgYpz_ZA](https://user-images.githubusercontent.com/91783814/180593462-b38d5c94-c922-454c-aca9-345a7eb7ad5a.png)

**Comment by RohanHBTU** [comment]
Hello Krishnendu, I have already registered for KSOC'22 and I'd like to work on this issue. May I?

**Comment by KrishnenduDakshi2002** [comment]
yeah sure @RohanHBTU, I've assigned you the issue. Happy contributing.

**Comment by KrishnenduDakshi2002** [comment]
If you can add colours other than the black white, that would be very nice.

**Comment by anuragc2001** [comment]
@RohanHBTU If you've completed the previous issue, I guess it's a good time to open a PR for the same. With that you'll be able to take up new issues.

**Comment by KrishnenduDakshi2002** [comment]
Hi @RohanHBTU 
Is there any progress in this issue?

**Comment by RohanHBTU** [comment]
Sorry for the delay, I am engaged in other affairs...PR will be coming shortly

**Comment by RohanHBTU** [comment]
> Hi @RohanHBTU 
> Is there any progress in this issue?

I have already worked on confusion matrix before so PR won't take much time, I got my classes to attend so my schedule is jam packed but I assure that this issue will be resolved soon enough.

**Comment by KrishnenduDakshi2002** [comment]
Closing this issue.
Issue is resolved in commit 0ad5a9a93f9fd0d2298a1b12012b3b1b9947c214
