### ISSUE TITLE
Add Polynomial Linear Regression

### ISSUE THREAD

**Issue by anuragc2001** [DSCKGEC/learn-machine-learn#9]
**Is your feature request related to a problem? Please describe.**
The polynomial linear regression block has been left incomplete. This feature will further help us to implement another regression model with which we can predict the model with more accuracy. 

**Describe the solution you'd like**
Implement Polynomial Regression on the given dataset given with the required preprocessed entities

**Comment by A1zenSousuke** [comment]
Hey @anuragc2001 can you assign this issue to me?

**Comment by anuragc2001** [comment]
@kpratik1929 Issue assigned! Go ahead.

**Comment by anuragc2001** [comment]
@kpratik1929 good work. Closing the issue.

**Comment by anuragc2001** [comment]
@kpratik1929 Please reopen a PR merging into the main branch directly.

**Comment by anuragc2001** [comment]
@kpratik1929 you've already submitted two PRs and I've approved of the changes. If you'd like to continue further I'd recommend you to take up more issues.

**Comment by anuragc2001** [comment]
@kpratik1929 please update the changes made in the repo and re-upload the code for polynomial regression. I'll not open the issue but please make a PR, just updating the polynomial regression code.
